docs: Update template
teamkaidee/iOS-clean-swift-templates pull request #2
Opened 2021-01-27 06:42 UTC by PH9

- Reduce setup steps. By always initial at variables
- Remove optional when it no need
- Remove `import UIKit` from worker, it should not use
- Remove `import UIKit` from the view model, it may not use
- Remove `MARK: Use cases` from the view model
- Remove router part from view controller. We do not prefer to use segue
- `MARK: Do something` to `MARK: - Actions`
- Remove `MARK: Do something` in the presenter
- `MARK: Setup` to `MARK: - Setup` and move to the above view controller constructor. It should not belong in the constructor function
- Move `IBOutlet` above everything, we are following the below order.
  1. Interface
  1. Outlets
  1. Local variables
  1. Initializations
  1. Object lift cycles
  1. Actions
- Remove white space in empty line
- Remove `tearDown()` from tests
- Remove `UIWindow` from tests, just call `_ = sut.view` is faster like a thousand times in unit testing. Except we want to working on some UI interaction.
- Remove NSObjectProtocol, @objc, NSObject, since it no use with Objective-C and Segue
- Separate presentation logic spy to file
- Separate business logic spy to file
- Separate display logic spy to file

If the change did not list here, I am sorry. Feel free to comment below.

2021-01-27 06:59 UTC, motojojoe requested changes

2021-01-28 01:52 UTC, PH9 commented
After discussion with @motojojoe and @chamnarns, the next PR will remove the worker from the interaction because we will share workers. Not one on no one like the template.

2021-01-28 03:26 UTC, motojojoe requested changes

2021-01-28 03:26 UTC, motojojoe commented on Clean Swift/Interactor.xctemplate/___FILEBASENAME___Interactor.swift
> +  func action(request: ___VARIABLE_sceneName___.Something.Request)
It doesn't look like use case. It's like action from UI.

2021-01-28 05:02 UTC, motojojoe approved these changes

2021-01-28 05:05 UTC, merged